name: 'financial_star_schema'
version: '1.0'
config-version: 2

profile: 'default'

model-paths: ["models"]

models:
  staging:
    +schema: 'staging'
    +materialized: 'view'
  dimensions:
    +schema: 'star_schema'
    +materialized: 'table'
  facts:
    +schema: 'star_schema'
    +materialized: 'table'
